name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.5,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -project CICDTest.xcodeproj -scheme CICDTest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
